services: memcache

bundler_args: --without development

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - DAEMON=1 bundle exec rake server

script: bundle exec rake spec spec:acceptance:rdb test

env:
  - TEST_MODE=rack
  - TEST_MODE=rdb
  - TEST_MODE=webrick
  - TEST_MODE=secure

gemfile:
  - Gemfile
  - misc/gemfiles/ruby18.gemfile

notifications:
  irc: "irc.freenode.org#tdiary"

matrix:
  exclude:
    # too bad exclude otpions.
    - rvm: 1.8.7
      env: TEST_MODE=rack
      gemfile: Gemfile
    - rvm: 1.8.7
      env: TEST_MODE=rdb
      gemfile: Gemfile
    - rvm: 1.8.7
      env: TEST_MODE=webrick
      gemfile: Gemfile
    - rvm: 1.8.7
      env: TEST_MODE=secure
      gemfile: Gemfile
    - rvm: 1.9.3
      env: TEST_MODE=rack
      gemfile: misc/gemfiles/ruby18.gemfile
    - rvm: 1.9.3
      env: TEST_MODE=rdb
      gemfile: misc/gemfiles/ruby18.gemfile
    - rvm: 1.9.3
      env: TEST_MODE=webrick
      gemfile: misc/gemfiles/ruby18.gemfile
    - rvm: 1.9.3
      env: TEST_MODE=secure
      gemfile: misc/gemfiles/ruby18.gemfile
    - rvm: 2.0.0
      env: TEST_MODE=rack
      gemfile: misc/gemfiles/ruby18.gemfile
    - rvm: 2.0.0
      env: TEST_MODE=rdb
      gemfile: misc/gemfiles/ruby18.gemfile
    - rvm: 2.0.0
      env: TEST_MODE=webrick
      gemfile: misc/gemfiles/ruby18.gemfile
    - rvm: 2.0.0
      env: TEST_MODE=secure
      gemfile: misc/gemfiles/ruby18.gemfile
  allow_failures:
    # webrick mode is unstable results...
    - env: TEST_MODE=webrick
